services:
  - type: web
    name: del-mar-race-analyzer
    env: python
    buildCommand: ./build.sh
    startCommand: ./start.sh
    envVars:
      - key: PORT
        sync: false
      - key: RELOAD
        value: "false"
      - key: LOG_LEVEL
        value: "info"
      - key: OPENROUTER_API_KEY
        sync: false
      - key: TWOCAPTCHA_API_KEY
        sync: false
      - key: ENVIRONMENT
        value: "production"
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: "/opt/render/project/.cache/ms-playwright"
    disk:
      name: del-mar-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
