services:
  - type: web
    name: del-mar-analyzer-docker
    runtime: docker
    dockerfilePath: render-deploy/Dockerfile
    dockerContext: ./
    plan: standard
    healthCheckPath: /health
    # Increase health check timeout to prevent restarts during long scraping operations
    healthCheckTimeout: 30
    healthCheckInterval: 60
    autoDeploy: false
    buildFilter:
      paths:
        - render-deploy/**
        - requirements.txt
        - app.py
        - "**/*.py"
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        value: sqlite:///./del_mar_analyzer.db
      - key: OPENROUTER_API_KEY
        fromSecret: openrouter-api-key
      - key: SECRET_KEY
        generateSecret: true
      - key: SCRAPER_USER_AGENT
        value: "Mozilla/5.0 (compatible; DelMar-Analyzer/1.0; +https://delmar-analyzer.onrender.com)"
      - key: SCRAPER_HEADLESS
        value: "true"
      - key: SCRAPER_TIMEOUT
        value: "45"
      - key: LOG_LEVEL
        value: "INFO"
      - key: DEBUG
        value: "false"
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: "/ms-playwright"
      - key: PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD
        value: "0"
    disk:
      name: del-mar-data
      mountPath: /app/data
      sizeGB: 1